db:
  user: "DATABASE_USERNAME"
  password: "DATABASE_PASSWORD"
  host: "DATABASE_HOST"
  name: "DATABASE_NAME"
  port: 5432
currency:
  - USD
  - RUB
  - EUR
  - UAH
  - TRY
  - KZT
proxy:
  protocol: 'https'
  host: '127.0.0.1'
  port: 9000
  auth:
    username: 'mikeymike'
    password: 'rapunz3l'