# For more information, see the documentation
# https://github.com/Redume/Kekkai/wiki

database: # Postgresql database data, for connection
  user: 'DATABASE_USERNAME'
  password: 'DATABASE_PASSWORD'
  host: 'DATABASE_HOST'
  name: 'DATABASE_NAME'
  port: 5432
server:
  host: 'localhost'
  ssl:
    private_key: '/CertSSL/private.key' # The path to the private SSL key file (String)
    cert: '/CertSSL/fullchain.pem' # The path to the SSL certificate (String)
    work: true # Enable or disable SSL support [Boolean]
  log:
    print: true # Enable or disable logging [Boolean]
    level: 'info' # Log level (Fatal/Error/Warn/Log/Debug) [String]
currency:
  chart:
    save: false # Enable or disable saving graphs to an image (Boolean)
  collecting:
    fiat: true # Turn off or turn on the collection of the fiat currency rate [Boolean]
    crypto: false # Turn off or turn on the collection of the cryptocurrency rate [Boolean]
    schedule: '30 8 * * *' # Currency collection schedule in crontab format [String]
  fiat: # List of fiat currency to save the exchange rate [Array]
    - USD
    - RUB
    - EUR
    - UAH
    - TRY
    - KZT
  crypto: # List of cryptocurrency to save the exchange rate [Array]
    - BTC
    - ETH
  coinapiKeys: # List of keys for the coinapi API [Array]
   - CryptoKey1
   - CryptoKey2
   - CryptoKey3