database:
  user: "DATABASE_USERNAME"
  password: "DATABASE_PASSWORD"
  host: "DATABASE_HOST"
  name: "DATABASE_NAME"
  port: 5432
server:
  host: localhost
  port: 5050
currency:
  collecting:
    fiat: True
    crypto: False
  fiat:
    - USD
    - RUB
    - EUR
    - UAH
    - TRY
    - KZT
  crypto:
    - BTC
    - ETH
