# For more information, see the documentation
# https://kekkai-docs.redume.su/

database: # Postgresql database data, for connection
  user: 'DATABASE_USERNAME'
  password: 'DATABASE_PASSWORD'
  host: 'DATABASE_HOST'
  name: 'DATABASE_NAME'
  port: 5432
server:
  host: '0.0.0.0'
  ssl:
    private_key: '/CertSSL/privkey.pem' # The path to the private SSL key file (String)
    cert: '/CertSSL/fullchain.pem' # The path to the SSL certificate (String)
    work: false # Enable or disable SSL support [Boolean]
  log:
    print: true # Enable or disable logging [Boolean]
    level: 'info' # Log level (Fatal/Error/Warn/Log/Debug) [String]
analytics:
    plausible_api: 'https://plausible.io/api/event/'
    plausible_domain: 'PLAUSIBLE_DOMAIN'
    plausible_token: 'PLAUSIBLE_TOKEN'
    work: false
currency:
  chart:
    save: false # Enable or disable saving graphs to an image (Boolean)
  collecting:
    fiat: true # Turn off or turn on the collection of the fiat currency rate [Boolean]
    schedule: '30 8 * * *' # Currency collection schedule in crontab format [String]
  fiat: # List of fiat currency to save the exchange rate [Array]
    - USD
    - RUB
    - EUR
    - UAH
    - TRY
    - KZT
