database:
  user: "DATABASE_USERNAME"
  password: "DATABASE_PASSWORD"
  host: "DATABASE_HOST"
  name: "DATABASE_NAME"
  port: 5432
server:
  host: 'localhost'
  private_key: '/CertSSL/private.key'
  cert: '/CertSSL/fullchain.pem'
  ssl: true
  debug: true
currency:
  collecting:
    fiat: True
    crypto: False
    schedule: '30 8 * * *'
  fiat:
    - USD
    - RUB
    - EUR
    - UAH
    - TRY
    - KZT
  crypto:
    - BTC
    - ETH
  coinapiKeys:
   - CryptoKey1
   - CryptoKey2
   - CryptoKey3