# Official documentation
# https://github.com/Redume/Kekkai/wiki/Config/

db:
  user: 'DATABASE_USERNAME'
  password: 'DATABASE_PASSWORD'
  host: 'DATABASE_HOST'
  name: 'DATABASE_NAME'
  port: 5432
server:
    host: localhost
    port: 3000
    logger: true # Enable or disable logs from fastify (true | false)
    ssl:
      privatekey: '' # The path where the SSL secret key is located (.key)
      cert: '' # The path where SSL certificate itself is located (.pem)
      enabled: false # Enable or disable SSL (true | false)
currency: # List of fiat currency for data collection.
  - USD
  - RUB
  - EUR
  - UAH
  - TRY
  - KZT
proxy:
  protocol: '' # Proxy Protocol (sock5 | sock4 | https)
  host: '127.0.0.1' # ipv4 servers where the proxy works
  port: 9000 # the port on which the proxy is running
  auth: # Authentication (optional)
    username: ''
    password: ''
