database:
  user: "DATABASE_USERNAME"
  password: "DATABASE_PASSWORD"
  host: "DATABASE_HOST"
  name: "DATABASE_NAME"
  port: 5432
server:
  host: localhost
currency:
  collecting:
    fiat: True
    crypto: False
  fiat:
    - USD
    - RUB
    - EUR
    - UAH
    - TRY
    - KZT
  crypto:
    - BTC
    - ETH
  cryptoKeys:
   - CryptoKey1
   - CryptoKey2
   - CryptoKey3
   - 8E06E31C-0F59-4CCE-9030-16573A5B6F1F
   - 187E449F-7610-4428-8A55-680978A6A151
   - DAB91062-2B69-43B0-BCB9-C9F65DDD185F