ktor:
  deployment:
    host: "localhost"
    port: 8080
  application:
    modules:
      - su.redume.ApplicationKt.module
  database:
    jdbcURL: "jdbc:postgresql://localhost:5432"
    database: "DATABASE_NAME"
    user: "DATABASE_USER"
    password: "DATABASE_PASSWORD"
    maxPoolSize: 50
    autoCommit: false