ktor:
  port: 3000
  host: localhost
database:
  jdbcURL: "jdbc:postgresql://localhost:5432"
  database: "DATABASE_NAME"
  user: "DATABASE_USER"
  password: "DATABASE_PASSWORD"
  maxPoolSize: 50
  autoCommit: false