name: Create and publish Docker images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/kekkai

permissions:
  contents: read
  packages: write

jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      server: ${{ steps.filter.outputs.server }}
      chart: ${{ steps.filter.outputs.chart }}
      web: ${{ steps.filter.outputs.web }}
      parser: ${{ steps.filter.outputs.parser }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'server/**'
            chart:
              - 'chart/**'
            web:
              - 'web/**'
            parser:
              - 'parser/**'

  build-and-push:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: server
            changed: ${{ needs.changes.outputs.server }}
            context: .
            file: ./server/Dockerfile
          - name: chart
            changed: ${{ needs.changes.outputs.chart }}
            context: ./chart
            file: ./chart/Dockerfile
          - name: web
            changed: ${{ needs.changes.outputs.web }}
            context: .
            file: ./web/Dockerfile
          - name: parser
            changed: ${{ needs.changes.outputs.parser }}
            context: .
            file: ./parser/Dockerfile

    if: ${{ matrix.changed == 'true' }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}-${{ matrix.name }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha
      - uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.file }}
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
